name: Build Debian Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    timeout-minutes: 1200
    steps:
      - uses: actions/checkout@v2
      - name: Build Debian Package
        run: |
          sudo npm install -g typescript
          COMMIT=$(git rev-parse HEAD | head -c 7)
          cd /tmp; git clone https://github.com/fade-project/fade
          cd fade; yarn install
          yarn start --init --name xenxenxense --path $GITHUB_WORKSPACE --version 0.0.0-$COMMIT-$PYTHON_VERSION \
          --description "A Modern RESTful API implemenation of XenAPI for Citrix Hypervisor(R) and XCP-ng." \
          --url "https://github.com/Stella-IT/XenXenXenSe" --priority optional --architecture all \
          --cmdline "python3 main.py" --dependency python$PYTHON_VERSION --dependency python3-pip \
          --maintainer-name "Stella IT" --maintainer-email "admin@stella-it.com" --type service
          node dist/ --edit --path $GITHUB_WORKSPACE --input-postinst-payload /dev/stdin << EOF
          sudo -H -u xenxenxense python3 -m pip install -r requirements.txt
          echo "WARNING: config.py is currently default; please edit before use."
          EOF
          node dist/ --create-deb --path $GITHUB_WORKSPACE --output $GITHUB_WORKSPACE/xenxenxense_0.0.0-$COMMIT-$PYTHON_VERSION\_all.deb
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}
      - name: Upload Debian Package
        uses: actions/upload-artifact@v2
        with:
          # Artifact name
          name: Debian Package - ${{ matrix.python-version }}
          # A file, directory or wildcard pattern that describes what to upload
          path: xenxenxense_0.0.0-*_all.deb
      - name: Test Debian Package
        run: |
          COMMIT=$(git rev-parse HEAD | head -c 7)
          sudo dpkg --ignore-depends=python$PYTHON_VERSION -i $GITHUB_WORKSPACE/xenxenxense_0.0.0-$COMMIT-$PYTHON_VERSION\_all.deb
        env:
            PYTHON_VERSION: ${{ matrix.python-version }}
